### PR TITLE
mb/system76: Configure I2C HID IRQs as level triggered

### PR DESCRIPTION
**Pull request by crawfxrd**
Upstream: [CB:61343](https://review.coreboot.org/c/coreboot/+/61343)

Per Microsoft's spec for [HID over I2C](http://download.microsoft.com/download/7/d/d/7dd44bb7-2a7a-4505-ac1c-7227d3d96d5b/hid-over-i2c-protocol-spec-v1-0.docx), interrupts must be level triggered. Switch GPIOs and the devicetree config to conform to this.

This affects

- [ ] addw1
- [ ] addw2
- [ ] bonw14
- [ ] darp5
- [ ] darp6
- [ ] gaze14
- [x] lemp9 - Tested by @jackpot51 
- [x] oryp6 - Tested by @crawfxrd 
- [x] oryp7 - Tested by @jacobgkau 

## How to test

- Blacklist PS/2 driver (boot with `modprobe.blacklist=psmouse`)
- Check dmesg for logs about touchpad device
- Check `/proc/bus/input/devices` for detected touchpad device
- Use `sudo libinput debug-gui` to check multitouch

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by crawfxrd** [comment]
oryp6

dmesg:

```
[    2.410535] psmouse serio1: synaptics: queried max coordinates: x [..5624], y [..4692]
[    2.463906] psmouse serio1: synaptics: queried min coordinates: x [1318..], y [1158..]
[    2.463920] psmouse serio1: synaptics: Your touchpad (PNP: PNP0f13) says it can support a different bus. If i2c-hid and hid-rmi are not used, you might want to try setting psmouse.synaptics_intertouch to 1 and report this to linux-input@vger.kernel.org.
[    2.575939] psmouse serio1: synaptics: Touchpad model: 1, fw: 10.48, id: 0x1e2a1, caps: 0xf00123/0x840300/0x2e800/0x52e48b, board id: 3621, fw id: 3174198
[    2.645185] input: SynPS/2 Synaptics TouchPad as /devices/platform/i8042/serio1/input/input6
[    3.413689] Console: switching to colour frame buffer device 240x67
[    3.427231] i915 0000:00:02.0: [drm] fb0: i915drmfb frame buffer device
[    6.484229] i2c_hid_acpi i2c-PNP0C50:00: failed to reset device.
[    7.669147] input: PNP0C50:00 06CB:CE25 Mouse as /devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-1/i2c-PNP0C50:00/0018:06CB:CE25.0001/input/input9
[    7.669763] input: PNP0C50:00 06CB:CE25 Touchpad as /devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-1/i2c-PNP0C50:00/0018:06CB:CE25.0001/input/input10
[    7.670346] hid-generic 0018:06CB:CE25.0001: input,hidraw0: I2C HID v1.00 Mouse [PNP0C50:00 06CB:CE25] on i2c-PNP0C50:00
```

`/proc/bus/input/devices`:

```
I: Bus=0018 Vendor=06cb Product=ce25 Version=0100
N: Name="PNP0C50:00 06CB:CE25 Mouse"
P: Phys=i2c-PNP0C50:00
S: Sysfs=/devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-1/i2c-PNP0C50:00/0018:06CB:CE25.0001/input/input27
U: Uniq=
H: Handlers=mouse0 event23 
B: PROP=0
B: EV=17
B: KEY=30000 0 0 0 0
B: REL=3
B: MSC=10

I: Bus=0018 Vendor=06cb Product=ce25 Version=0100
N: Name="PNP0C50:00 06CB:CE25 Touchpad"
P: Phys=i2c-PNP0C50:00
S: Sysfs=/devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-1/i2c-PNP0C50:00/0018:06CB:CE25.0001/input/input28
U: Uniq=
H: Handlers=mouse1 event24 
B: PROP=1
B: EV=1b
B: KEY=e520 30000 0 0 0 0
B: ABS=2e0800000000003
B: MSC=20
```

**Comment by jackpot51** [comment]
```
[    6.484229] i2c_hid_acpi i2c-PNP0C50:00: failed to reset device.
```

Is this not a problem?

**Comment by crawfxrd** [comment]
> Is this not a problem?

I only see this if psmouse logs first, so I assume it's related to psmouse initializing before i2c-hid.

I don't see it on any other boots, in which i2c-hid logs first or I have psmouse blacklisted.

**Comment by jacobgkau** [comment]
On oryp7, I saw multitouch still working (with or without blacklisting `psmouse`) even on the current master branch without this fix. The fix does not seem to cause any regressions, though. Can confirm that while booted with the blacklist option set, multitouch works in the libinput debug GUI, `/proc/bus/input/devices` shows the touchpad, and there is no change in dmesg logging for touchpad or input before and after the change.

**Comment by crawfxrd** [comment]
We should also check before/after behavior on Windows. It is a Microsoft spec, after all.

**Comment by jacobgkau** [comment]
Touchpad was already working in the Windows 10 installer with master firmware on oryp7. After the change, still works in the installer and after installing.

I'm trying to test on bonw14 too, but I'm having trouble getting it to boot at all after flashing master + this branch (was previously running released firmware.)

**Comment by jackpot51** [comment]
Merged as part of #101

**Pull request closed without merging**
