### PR TITLE
soc/intel/meteorlake: Set UsbTcPortEn based on tcss_port[x] (ported from alderlake)

### PR DESCRIPTION
**Pull request by tobiasfunke1**
Looks like for the Darter Pro 10 (Meteor Lake) there is the same bug with the usb3 solved in https://github.com/system76/coreboot/pull/227 for Raptor Lake and Alder Lake.

So I just ported the code to Meteor Lake, but I was not be able to test it yet. Can someone confirm that the patch is working?

Seams to be related to https://github.com/system76/firmware-open/issues/511 and https://github.com/system76/firmware-open/issues/497 but both using Raptor Lake so it seams to be fixed after the patch. Here is the related PR https://github.com/system76/firmware-open/pull/556.

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jackpot51** [comment]
The code looks fine. I've asked for QA to check this out, and Tim who wrote the patch for ADL

**Comment by crawfxrd** [comment]
The ADL patch is from https://review.coreboot.org/c/coreboot/+/82058.

There is also https://review.coreboot.org/c/coreboot/+/80500 for FSP-M.

**Review by leviport — CHANGES_REQUESTED** [review]
I've confirmed that the USB-C ports are running at 2.0 speeds on darp10 and darp10-b. After flashing this patch, however, I'm not seeing the speeds increase to expected speeds.

For testing, I'm using an NVMe in a USB-C caddy, and using the "Benchmark" utility built into Gnome Disks. On darp10 & darp10-b, it averages ~45 MB/s. The same drive on the USB-C ports on lemp13 hits roughly 1 GB/s.

**Comment by leviport** [comment]
I recall the USB-C ports running at 2.0 speeds on lemp13 during product development as well, but I'm having trouble finding which commit fixed that. This one looks like it might be promising? https://github.com/system76/coreboot/pull/213/commits/828cf021f22dea4ce676610d8b30634630a6905e

**Comment by tobiasfunke1** [comment]
@leviport Thanks for the confirmation of the problem and trying the suggested patch. Since the patch is not working and you mentioned a commit that may work, can you check if it fixes the issue?

Should we create an issue for that problem now?

**Comment by leviport** [comment]
I rebuilt and flashed darp10-b firmware with the latest `system76` branch of coreboot checked out, and the USB-C ports are still benchmarking at 2.0 speeds. So despite that commit fixing lemp13, it seems something different needs to be done for darp10.

**Comment by tobiasfunke1** [comment]
Hi @theguy147, I looked into it and this makes sense to me.

As I can see it, when @jackpot51 added the lemp13 in bcd34461da120bfeb43ab13c2b71df878efe73e7, he registered the tcss_ports. Those were not registered for the darp10 in 49122b0ec53f3a31959f2c0903468f0139077d7c by @crawfxrd.

Can someone please confirm, that this makes sense and test if this patch works now?

**Comment by leviport** [comment]
I'll give it a re-test soon!

**Comment by leviport** [comment]
Now I'm getting ~1GB/s speeds on the back (thunderbolt) USB-C port, but I'm still seeing ~45MB/s on the front (non-TB) port. An improvement! 

Lemp13 also has two USB-C's, one of which is TB. However, both USB-C's on lemp13 support USB 3.x speeds. I wonder what else is required to enable full speed on the front USB-C port as well?

**Comment by leviport** [comment]
We do have schematics available: https://github.com/system76/firmware-open/blob/master/docs/schematics.md

That should make things much easier than following traces manually, at least.

**Comment by tobiasfunke1** [comment]
Thanks to @theguy147 for going trough the schematics of the darp10.

I have updated the PR with the new ACPI configuration, @leviport can you please check if it still works and if the non-TB port works now?

**Comment by leviport** [comment]
Yep, I'll give it a try today!

**Comment by tobiasfunke1** [comment]
There is a Dasharo coreboot meteorlake branch, where the devicetree.cb for the clevo mainboard looks like this https://github.com/Dasharo/coreboot/blob/mtl-h/src/mainboard/clevo/mtl-h/devicetree.cb#L105-L124.

This confirms that we are on the right way. :)

**Comment by leviport** [comment]
Sorry to report back with bad news, but that pesky front USB-C port is still benchmarking around ~45MB/s with the latest update. The rear (TB) port is still looking good at over ~1GB/s though.

**Comment by tobiasfunke1** [comment]
Seems to be legit, there is a similar initialization for the lemp13: https://github.com/system76/coreboot/blob/system76/src/mainboard/system76/mtl/variants/lemp13/ramstage.c

I will add it to the patch.

**Comment by tobiasfunke1** [comment]
Done, @leviport can you please confirm that the patch works for you too?

**Comment by leviport** [comment]
Will do!

**Review by leviport — APPROVED** [review]
Fix confirmed! Benchmark speeds on both USB-C ports are faster than 2.0 specs. Both ports also still support PD charging. I double-checked TB and DP on the back port, and both are still working nicely. Thanks for all the help on this fix!

**Review by crawfxrd — APPROVED** [review]

**Comment by crawfxrd** [comment]
Still no way to manually mark things as merged on GitHub.

Applied as:

- a1b808e08213 ("mb/system76/darp10: Add TCSS configs")
- 7877cab8da9f ("soc/intel/meteorlake: Set UsbTcPortEn based on tcss_port[x]")

**Pull request closed without merging**
