### PR TITLE
lemp9 fixes

### PR DESCRIPTION
**Pull request by jackpot51**
- [x] Fix lemp9 backlight ACPI issues
- [x] Fix TPM error message

### CODE REVIEW

**Review by crawfxrd — APPROVED** [review]

**Comment by bflanagin** [comment]
I don't have enough information on what the ACPI issue is to report back on whether its fixed.  There does seem to be something going on though, this is from dmesg:

```
[    2.205664] [Firmware Bug]: ACPI(GFX0) defines _DOD but not _DOS
[    2.205703] ACPI: Video Device [GFX0] (multi-head: yes  rom: no  post: no)
[    2.205709] ACPI BIOS Error (bug): Could not resolve symbol [^^XBCL], AE_NOT_FOUND (20200528/psargs-330)
[    2.205716] No Local Variables are initialized for Method [_BCL]
[    2.205717] No Arguments are initialized for method [_BCL]
[    2.205718] ACPI Error: Aborting method \_SB.PCI0.GFX0.LCD0._BCL due to previous error (AE_NOT_FOUND) (20200528/psparse-529)
[    2.205829] ACPI BIOS Error (bug): Could not resolve symbol [^^XBCL], AE_NOT_FOUND (20200528/psargs-330)
[    2.205833] No Local Variables are initialized for Method [_BCL]
[    2.205834] No Arguments are initialized for method [_BCL]
[    2.205835] ACPI Error: Aborting method \_SB.PCI0.GFX0.LCD0._BCL due to previous error (AE_NOT_FOUND) (20200528/psparse-529)
```

**Comment by jackpot51** [comment]
@bflanagin that is the error that I saw before, and the changes made in this PR ought to fix it.

**Comment by bflanagin** [comment]
Ah, so I screwed something up the first time around and didn't flash the right firmware. Everything is checking out on Windows and Pop!_OS. Unless you want any outputs from anything I'm ready to approve.

**Review by bflanagin — APPROVED** [review]
Issues resolved (as far as dmesg reports). Tested stability issue in windows as well as regression tests on Pop! 

All is well.

**Pull request merged**
