### PR TITLE
Perform TPM restart if TPM resume fails

### PR DESCRIPTION
**Pull request by crawfxrd**
Fixes TPM errors being logged every ~10 seconds when the Infineon chip fails TPM Resume.

Fixes: https://github.com/system76/firmware-open/issues/427

### CODE REVIEW

**Comment by leviport** [comment]
I'm still getting TPM errors on both serw13 lab units. I'll try the addw3 next so we have another data point though.

**Comment by leviport** [comment]
I left the addw3 doing suspend tests overnight, and it also had TPM errors in the logs this morning. All units were flashed with `master` from firmware-open, but with the `tpm-delay` branch checked out in the Coreboot submodule.

**Comment by crawfxrd** [comment]
```
[INFO ]  Found TPM unknown by Infineon
[INFO ]  TPM: Handle S3 resume.
[INFO ]  tlcl_send_startup: Startup return code is 1c4
[ERROR]  TPM: Resume failed (0x1f).
```

**Review by jackpot51 — APPROVED** [review]

**Comment by crawfxrd** [comment]
50 usec is probably excessive to wait for the chip, but should fix using the Infineon SLB 9672.

---

The schematics say "FW 15.21". I don't know if that's *really* what's on them, but there does seem to be a 15.22 firmware...somewhere.

**Comment by crawfxrd** [comment]
And apparently it's not good enough. I eventually triggered the issue even with 50us.

Might try something absurd like 1ms.

And if that doesn't work...I guess I'll actually look for what `TPM_RC_VALUE` means and if this can be waited on or be retried.

**Comment by crawfxrd** [comment]
From https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part3_Commands_code_pub.pdf

> If a TPM receives Startup(STATE) and that was not preceded by Shutdown(STATE), the TPM shall return TPM_RC_VALUE.

> TPM_RC_VALUE | start up type is not compatible with previous shutdown sequence

But then I'd expect us to always get this, since coreboot doesn't send Shutdown at all.

I guess it could be also be unmarshalling?:

> TPM_RC_VALUE | a parameter does not have one of its allowed values

**Comment by crawfxrd** [comment]
attempting to start/shutdown the TPM from Linux in this state fails

```
$ sudo tpm2_startup
ERROR:tcti:src/tss2-tcti/tcti-device.c:503:Tss2_Tcti_Device_Init() timeout waiting for response from fd 3
WARNING:esys:src/tss2-esys/api/Esys_Startup.c:212:Esys_Startup_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_Startup.c:78:Esys_Startup() Esys Finish ErrorCode (0x000001c4)
ERROR: Esys_Startup(0x1C4) - tpm:parameter(1):value is out of range or is not correct for the context
ERROR: Unable to run tpm2_startup
```

```
$ sudo tpm2_shutdown
ERROR:tcti:src/tss2-tcti/tcti-device.c:503:Tss2_Tcti_Device_Init() timeout waiting for response from fd 3
WARNING:esys:src/tss2-esys/api/Esys_Shutdown.c:269:Esys_Shutdown_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_Shutdown.c:95:Esys_Shutdown() Esys Finish ErrorCode (0x00000100)
ERROR: Esys_Shutdown(0x100) - tpm:error(2.0): TPM not initialized by TPM2_Startup or already initialized
ERROR: Unable to run tpm2_shutdown
```

**Comment by crawfxrd** [comment]
Now performs a TPM restart if the TPM resume fails:

```
[INFO ]  Found TPM SLB9672 TT 2.0 by Infineon
[INFO ]  TPM: Handle S3 resume.
[INFO ]  tlcl_send_startup: Startup return code is 1c4
[ERROR]  TPM: Resume failed (0x1f).
[WARN ]  TPM: Clearing state
[INFO ]  tlcl_send_startup: Startup return code is 0
[INFO ]  TPM: setup succeeded
[DEBUG]  BS: BS_DEV_INIT exit times (exec / console): 38 / 0 ms
[INFO ]  POST: 0x76
```

**Review by jackpot51 — APPROVED** [review]

**Comment by XV-02** [comment]
So, I've done 300 suspend tests on Oryp11 built from firmware-open with this PR checked out in coreboot. 

I've not seen any of the prior TPM errors crop up, but I've also not seen anything in the output for cbmem matching the `Clearing state` message. 

But, given that I'm not seeing the errors, I'm inclined to approve, unless there's any reason not to?

**Review by XV-02 — APPROVED** [review]
Looks good. `cbmem`'s short buffer makes catching the `Clearing state` message hard, but the lack of TPM errors in system logs across 300 suspends on Oryp11 suggests this has resolved the underlying issue spawning the log spam.

**Pull request merged**
