### PR TITLE
Fix galp5 DGPU ACPI path

### PR DESCRIPTION
**Pull request by jackpot51**
It is remapped from RP05 to RP01 because there is no RP01.

### CODE REVIEW

**Review by crawfxrd — APPROVED** [review]
Does this happen to fix system76/firmware-open#287?

**Comment by leviport** [comment]
I believe https://github.com/system76/firmware-open/issues/287 still persists:

Annotation 2022-02-16 162628

I did not install any additional drivers after installing Windows though, so I can try that too.

**Comment by jackpot51** [comment]
Ok, might want to check #97

**Comment by jackpot51** [comment]
Moved to #101

**Pull request closed without merging**
