### PR TITLE
mb/system76/adl,rpl,tgl-h: Enable DRIVERS_GENERIC_BAYHUB_LV2 to fix LTR issue

### PR DESCRIPTION
**Pull request by jackpot51**
This should reduce idle power usage on the following systems, that use the SD card controller with the ID `1217:8621`. Please ensure they are all entering the C8 state as shown in `powertop`.

- [ ] addw3
- [ ] darp8
- [ ] darp9
- [ ] galp6
- [ ] galp7
- [ ] gaze16-3050
- [ ] gaze16-3060
- [ ] gaze16-3060-b
- [ ] gaze17-3050
- [ ] gaze17-3060-b
- [ ] gaze18
- [ ] lemp11
- [ ] lemp12
- [ ] oryp10
- [ ] oryp11
- [ ] oryp9
- [ ] serw13

### CODE REVIEW

**Review by crawfxrd — APPROVED** [review]
lemp12 (with screen at 50% brightness) discharge rate reduced from ~7.8W to ~4.6W.

May need further investigation. CPU only goes to C6 when idle, not C8.

**Comment by XV-02** [comment]
I built firmware for galp7 using this PR. I should see various c-states listed when I launch powertop, I believe. However, I don't see a listing for anything other than power states c1 and c2.

**Comment by crawfxrd** [comment]
powertop 2.15 is required for RPL. Use `/sys/kernel/debug/pmc_core/package_cstate_show` instead.

**Comment by jackpot51** [comment]
@XV-02 it seems powertop does not currently support RPL systems. You see time spent in package c-states with:

```
sudo cat /sys/kernel/debug/pmc_core/package_cstate_show
```

**Comment by jacobktm** [comment]
> I built firmware for galp7 using this PR. I should see various c-states listed when I launch powertop, I believe. However, I don't see a listing for anything other than power states c1 and c2. Is that likely a powertop issue or a PR issue?

I built firmware for darp9 using this PR and I see the same thing, the only power states in powertop are c1 and c2. I've found that the [intel_idle](https://github.com/pop-os/linux/blob/master/drivers/idle/intel_idle.c) driver in the linux kernel doesn't support raptor lake, so it falls back to whatever's in the ACPI tables for the system. I built a custom kernel that added RPL support to intel_idle by just pointing raptor lake to alder lake's supported c-states (which is probably not technically correct, but it seems to work), and it even gets the darp9 an additional watt lower. from around 9watts with the display at 100% to 8 watts.

**Comment by jackpot51** [comment]
We should then also bring intel_idle updates to our kernel: https://lore.kernel.org/lkml/e11f89efc67ec90ba1fed21bbfeb4af8764119e9.camel@intel.com/T/

**Comment by jacobktm** [comment]
> We should then also bring intel_idle updates to our kernel: https://lore.kernel.org/lkml/e11f89efc67ec90ba1fed21bbfeb4af8764119e9.camel@intel.com/T/
> 
> ```
> RPL and ADL have same cstates and use the same mwait hints, but the
> latency of each c-state are still different on different platforms.
> So we can not just duplicate the ADL table on RPL.
> 
> There is an effort ongoing that measures the latency of each
> cstate on the RPL platforms. And based on the measurement result, we
> can decide if a new custom table is needed or we can just copy the
> previous platform. Hopefully we will have a patch in a couple of weeks.
> ```

That's funny, I thought I had to be doing it wrong, but that's exactly how I did it.

**Comment by jackpot51** [comment]
I sent an email about this to Rui.

**Comment by XV-02** [comment]
Well, for the moment, I'm only seeing Galp7 dipping into C6, with no evidence of hitting C8, despite C8 availability on raptor lake per intel documention.

**Comment by jackpot51** [comment]
Before this change, it should not be able to go below PC2.

**Comment by XV-02** [comment]
That is correct, but the specific callout was for C8, and I'm not seeing that on Galp7.

Gaze17-3060-B, however, does report C8, as opposed to only hitting C2 recently.

**Comment by jackpot51** [comment]
I am pretty sure we will need intel_idle updated as mentioned before to go to C8 state, along with this PR.

**Pull request merged**
