### PR TITLE
Enable 5200MHz memory on addw3, bonw15, and serw13

### PR DESCRIPTION
**Pull request by jackpot51**

### CODE REVIEW

**Comment by jackpot51** [comment]
@leviport is the 5200 MT/s memory using XMP?

**Comment by leviport** [comment]
I believe they are native 5200 MT/s

**Comment by jackpot51** [comment]
I'm trying a different way to turn this on, please see the latest commit

**Comment by crawfxrd** [comment]
```
# !BSF HELP:{Maximum Memory Frequency Selections in Mhz. Options are 1067, 1333, 1600, 1867, 2133, 2400, 2667, 2933 and 0 for Auto.}
```

Does this work? Did Intel just never update this in 10 years?

**Review by leviport — APPROVED** [review]
Looks good on addw3!

**Review by crawfxrd — APPROVED** [review]

**Pull request merged**
