### PR TITLE
Apply HDA verb table change from serw13 to oryp11 and bonw15

### PR DESCRIPTION
**Pull request by leviport**
serw13 change: https://github.com/system76/coreboot/commit/e6f70bdcb5ad03f8a2e4b14e09a5da1d174a9a73

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by ahoneybun** [comment]
This seems to cause the NVMe drive to not appear anymore and it causes the speaker to not work anymore. Reverting back to release firmware fixes both issues though the main issue is still there.

**Comment by XV-02** [comment]
> This seems to cause the NVMe drive to not appear anymore and it causes the speaker to not work anymore. Reverting back to release firmware fixes both issues though the main issue is still there.

Which system - Oryp11 or Bonw15?
Which NVMe and which NVMe slot?

**Comment by ahoneybun** [comment]
@XV-02 bonw15 though not sure about the NVMe slot.

**Comment by ahoneybun** [comment]
@XV-02 the firmware that you flashed on this system causes the issue to go away and I can't recreate it now. I'm also attaching the file that we are using to test.

https://github.com/system76/coreboot/assets/4884946/69c2e183-5fd7-484a-a15d-e5323d96a4d5

**Review by XV-02 — APPROVED** [review]
@ahoneybun Sweet!

Looks like the first flash on known-bad system wasn't stable. Subsequent flashes behaved as desired though. On the lab unit, I was able to flash back and forth a few times without issues, either. 

The Oryp11 we received from Sager was also exhibiting audio cut out which this seems to have resolved without introducing any obvious regressions on either the lab unit nor the known-bad unit.

Looks good to merge.

**Comment by crawfxrd** [comment]
upstream: [CB:78511](https://review.coreboot.org/c/coreboot/+/78511)

**Pull request merged**
