### PR TITLE
Gc6 2

### PR DESCRIPTION
**Pull request by jackpot51**

### CODE REVIEW

**Comment by crawfxrd** [comment]
Got this error this morning on oryp5:
```
ACPI Debug:  "NVIDIA _PS3 {"
ACPI Debug:  "} NVIDIA _PS3"
ACPI Debug:  "NVIDIA PWRR._OFF {"
ACPI Debug:  "NVIDIA _OFF {"
ACPI Debug:  "  LTRE = 0000000000000001"
ACPI Debug:  "RTDS {"
ACPI Debug:  "  Q0L2 = 1"
ACPI Debug:  "  Sleep 16"
ACPI Debug:  "  While Q0L2"
ACPI Debug:  "  P0RM = 1"
ACPI Debug:  "  P0AP = 3"
ACPI Debug:  "} RTDS"
ACPI Debug:  "NVIDIA GPPR: 0000000000000000 {"
ACPI Debug:  "  DGPU_RST_N low"
ACPI Debug:  "  Sleep 0000000000000002"
ACPI Debug:  "  DGPU_PWR_EN low"
ACPI Debug:  "} NVIDIA GPPR: 0000000000000000"
ACPI Debug:  "  _STA = 0x5"
ACPI Debug:  "} NVIDIA _OFF"
ACPI Debug:  "} NVIDIA PWRR._OFF"
ACPI Debug:  "NVIDIA PWRR._ON {"
ACPI Debug:  "NVIDIA _ON {"
ACPI Debug:  "NVIDIA GPPR: 0000000000000001 {"
ACPI Debug:  "  DGPU_PWR_EN high"
ACPI Debug:  "  Sleep 0000000000000007"
ACPI Debug:  "  DGPU_RST_N high"
ACPI Debug:  "  Sleep 0000000000000002"
ACPI Debug:  "} NVIDIA GPPR: 0000000000000001"
ACPI Debug:  "RTEN {"
ACPI Debug:  "  Q0L0 = 1"
ACPI Debug:  "  Sleep 16"
ACPI Debug:  "  While Q0L0"
ACPI Debug:  "  P0RM = 0"
ACPI Debug:  "  P0AP = 0"
ACPI Debug:  "} RTEN"
ACPI Debug:  "  While P0LS < 7"

Initialized Local Variables for Method [_ON_]:
  Local0: 00000000fb7d4f84 <Obj>           Integer 0000000000000000
No Arguments are initialized for method [_ON_]
ACPI Error: Aborting method \_SB.PCI0.PEGP.DEV0._ON due to previous error (AE_AML_LOOP_TIMEOUT) (20200528/psparse-529)
ACPI Error: Aborting method \_SB.PCI0.PEGP.DEV0.PWRR._ON due to previous error (AE_AML_LOOP_TIMEOUT) (20200528/psparse-529)
acpi device:42: Failed to change power state to D0
nvidia 0000:01:00.0: can't change power state from D3cold to D0 (config space inaccessible)
NVRM: GPU at PCI:0000:01:00: GPU-87d980de-a105-0db8-f31f-87d642dd3998
NVRM: Xid (PCI:0000:01:00): 79, pid=282, GPU has fallen off the bus.
NVRM: GPU 0000:01:00.0: GPU has fallen off the bus.
NVRM: A GPU crash dump has been created. If possible, please run
NVRM: nvidia-bug-report.sh as root to collect this data before
NVRM: the NVIDIA kernel module is unloaded.
```

**Comment by crawfxrd** [comment]
Had the error on oryp6 on boot.

```
$ cat /sys/module/nvidia/version 
460.32.03
```

```
[   37.420349] ACPI Debug:  "NVIDIA _PS3 {"
[   37.420364] ACPI Debug:  "} NVIDIA _PS3"
[   37.420372] ACPI Debug:  "NVIDIA PWRR._OFF {"
[   37.420380] ACPI Debug:  "NVIDIA _OFF {"
[   37.420389] ACPI Debug:  "NVIDIA GC6I {"
[   37.420432] ACPI Debug:  "  LTRE = 0000000000000001"
[   37.420440] ACPI Debug:  "RTDS {"
[   37.420442] ACPI Debug:  "  Q0L2 = 1"
[   37.420447] ACPI Debug:  "  Sleep 16"
[   37.444311] ACPI Debug:  "  While Q0L2"
[   37.444329] ACPI Debug:  "  P0RM = 1"
[   37.444336] ACPI Debug:  "  P0AP = 3"
[   37.444342] ACPI Debug:  "} RTDS"
[   37.444349] ACPI Debug:  "  Sleep 10"
[   37.464315] ACPI Debug:  "  DGPU_RST_N low"
[   37.464549] ACPI Debug:  "} NVIDIA GC6I"
[   37.464556] ACPI Debug:  "  While DGPU_GC6 low"
[   37.772875] ACPI Debug:  "    While DGPU_GC6 low timeout"
[   37.772892] ACPI Debug:  "    DGPU_PWR_EN low"
[   37.773281] ACPI Debug:  "  _STA = 0x5"
[   37.773305] ACPI Debug:  "} NVIDIA _OFF"
[   37.773330] ACPI Debug:  "} NVIDIA PWRR._OFF"
[   37.773387] ACPI Debug:  "NVIDIA PWRR._ON {"
[   37.773420] ACPI Debug:  "NVIDIA _ON {"
[   37.773448] ACPI Debug:  "  If DGPU_PWR_EN low"
[   37.773838] ACPI Debug:  "    DGPU_PWR_EN high"
[   37.774207] ACPI Debug:  "    Sleep 16"
[   37.796352] ACPI Debug:  "NVIDIA GC6O {"
[   37.796371] ACPI Debug:  "  DGPU_RST_N high"
[   37.796867] ACPI Debug:  "  Sleep 10"
[   37.816372] ACPI Debug:  "RTEN {"
[   37.816391] ACPI Debug:  "  Q0L0 = 1"
[   37.816418] ACPI Debug:  "  Sleep 16"
[   37.840365] ACPI Debug:  "  While Q0L0"
[   37.840418] ACPI Debug:  "  P0RM = 0"
[   37.840441] ACPI Debug:  "  P0AP = 0"
[   37.840461] ACPI Debug:  "} RTEN"
[   37.840582] ACPI Debug:  "  LREN = 0000000000000001"
[   37.840607] ACPI Debug:  "  CEDR = 1"
[   37.840700] ACPI Debug:  "  CMDR |= 7"
[   37.840759] ACPI Debug:  "} NVIDIA GC6O"
[   37.840776] ACPI Debug:  "  _STA = 0xF"
[   37.840796] ACPI Debug:  "} NVIDIA _ON"
[   37.840820] ACPI Debug:  "} NVIDIA PWRR._ON"
[   37.840855] ACPI Debug:  "NVIDIA _PS0 {"
[   37.840882] ACPI Debug:  "} NVIDIA _PS0"
[   37.840902] nvidia 0000:01:00.0: can't change power state from D3cold to D0 (config space inaccessible)
[   37.840952] NVRM: GPU at PCI:0000:01:00: GPU-c9ed20ba-4c45-946e-4ed6-616892890b92
[   37.840960] NVRM: Xid (PCI:0000:01:00): 79, pid=7, GPU has fallen off the bus.
[   37.840963] NVRM: GPU 0000:01:00.0: GPU has fallen off the bus.
[   37.842334] xhci_hcd 0000:01:00.2: can't change power state from D3cold to D0 (config space inaccessible)
[   37.842356] xhci_hcd 0000:01:00.2: can't change power state from D3hot to D0 (config space inaccessible)
[   37.842366] xhci_hcd 0000:01:00.2: Controller not ready at resume -19
[   37.842369] xhci_hcd 0000:01:00.2: PCI post-resume error -19!
[   37.842372] xhci_hcd 0000:01:00.2: HC died; cleaning up
```

**Comment by benjamindoron** [comment]
I can't comment at all on the xHCI error.

Regarding the first error: The issue appears to be that the method tries to guarantee that the link will come up, and will set the "retrain link" bit after every 'timeout' until it does (I haven't examined the datasheet to find the exact bits, but this appears to be the purpose based on the uses and names). The issue is that this gets aborted (AE_AML_LOOP_TIMEOUT, from the log) if it takes too long, which is registered as a significant error.

I've had luck with a much simpler `While (LNKS < 0x7) {Sleep (5)}` (here, LNKS should be equivalent to P0LS), although I'm not certain what to make the "sleep" time. Alternatively, you could loop for a fixed number of "sleeps" and break if the link comes up.

If I recall correctly, if the link doesn't come up, the drivers just try again.

Regarding the second error: It appears to me that since _PS3 will only execute after Optimus sets flags, the named status variable is not updated. As a result, _PS0 skips execution, so the link is not brought up.

**Comment by jackpot51** [comment]
Replaced by #98

**Pull request closed without merging**
