### PR TITLE
Rebase on 4.17

### PR DESCRIPTION
**Pull request by crawfxrd**
Update from the ~4.16 base to 4.17 release.

Current branch is preserved as `system76-4.16`.

### CODE REVIEW

**Comment by linuxgnuru** [comment]
Built and flashed on `galp5` and `lemp9` without issues, `sudo dmidecode -t 0` shows `BIOS Revision: 4.15` should this now be 4.17?

**Review by linuxgnuru — APPROVED** [review]
Tested on `lemp9`, `galp5`, `gaze16-3050ti`, and `oryp7` and everything built and flashed without issues. 

After flashing, the command  `sudo dmidecode -t 0` shows:
```
system76@pop-os:~$ sudo dmidecode -t 0
[sudo] password for system76:
# dmidecode 3.3
Getting SMBIOS data from sysfs.
SMBIOS 3.3.0 present.

Handle 0x0000, DMI type 0, 26 bytes
BIOS Information
	Vendor: coreboot
	Version: 2022-06-07_090f9e0-dirty
	Release Date: 06/08/2022
	ROM Size: 16 MB
	Characteristics:
		PCI is supported
		PC Card (PCMCIA) is supported
		BIOS is upgradeable
		Selectable boot is supported
		ACPI is supported
		Targeted content distribution is supported
	BIOS Revision: 4.17
	Firmware Revision: 0.0
```

**Comment by crawfxrd** [comment]
I have to retest on gaze17. I saw the GPU not being detected.

**Review by 13r0ck — APPROVED** [review]

**Comment by crawfxrd** [comment]
After gaze17-3050, I will rebase on a newer commit and push it.

**Pull request closed without merging**
