### PR TITLE
mb/system76: Update HDA codec configs

### PR DESCRIPTION
**Pull request by crawfxrd**
- Reset codec before configuring (I don't know if this affects behavior on anything besides oryp5, but proprietary firmware does it and it seems like a good idea in general.)

Test:

- 3.5mm jacks, built-in microphone, speakers work
  - after cold boot
  - after warm boot
  - after S3 suspend (if applicable)

### CODE REVIEW

**Comment by XV-02** [comment]
This worked fine on Lemp9. Need to investigate other effected models still.

**Comment by XV-02** [comment]
Other firmware builds without obvious issues. Needs flashing for testing.

**Comment by XV-02** [comment]
Gaze17 3060 works.

**Comment by crawfxrd** [comment]
The ALC256 datasheet has this note:

> In the ALC256, when in the extended power state conforming to Intel’s low power DCN, the reset function cannot not initialize the register setting. The Host SW needs to send ‘two’ function resets consecutively to reset all settings.

So would `AZALIA_RESET(1)` be required twice on those boards?

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
