### PR TITLE
the i9-13900HX supports up to 128GB 5600 MT/s DDR5 memory

### PR DESCRIPTION
**Pull request by ilikenwf**
See

https://ark.intel.com/content/www/us/en/ark/products/232171/intel-core-i913900hx-processor-36m-cache-up-to-5-40-ghz.html

### CODE REVIEW

**Comment by ilikenwf** [comment]
I have 2x32GB Kingston DDR5 5600 in mine and this does work properly, or at least it does according to dmidecode.

**Comment by jackpot51** [comment]
I will need to talk with our motherboard manufacturer for these to see if 5600 MT/s is supported. It needs both CPU and motherboard support. It also may work on your system, but potentially have issues on others due to variance. We are certain that 5200 MT/s is supported, and I will let you know if the motherboard manufacturer believes we can enable 5600 MT/s support on all produced systems.

**Comment by ilikenwf** [comment]
No problem - I realize I'm a bit reckless, but it is the nature of open source at times. Any suggestions on benchmarking or testing I should run to see if it is fully stable? My day to day stuff seems fine...

**Comment by ilikenwf** [comment]
I'll do that once I get a moment. Also to be fair, I won't mention the name of your manufacturer because I bought from you for the support and to support your firmware efforts, but the configurator for similar models to mine includes 5600 when using their properitary firmware, at least.

**Comment by ilikenwf** [comment]
As an unrelated aside, if I wanted to use the HAP bit to be sure ME was fully disabled as possible, do you happen to know the address for our ME image to set that bit? I realize it may mean 3W sleep instead of 1W, but it may be worth living with to quell my paranoia.

I know I've made a lot of noise but I am one of those people who gets joy out of experimenting with/customizing his tech, so I hope I don't become annoying.

**Review by jackpot51 — APPROVED** [review]
I have comfirmed 5600 MT/s is supported by these motherboards.

**Comment by ilikenwf** [comment]
Awesome!

**Comment by leviport** [comment]
@ilikenwf  I don't have any 5600MT/s SODIMMs to test with here, so I will approve if your MemTest86 results look good. Please share them when they are complete.

**Comment by jackpot51** [comment]
> As an unrelated aside, if I wanted to use the HAP bit to be sure ME was fully disabled as possible, do you happen to know the address for our ME image to set that bit? I realize it may mean 3W sleep instead of 1W, but it may be worth living with to quell my paranoia.
> 
> I know I've made a lot of noise but I am one of those people who gets joy out of experimenting with/customizing his tech, so I hope I don't become annoying.

I'm not sure of the HAP bit on 13th gen platforms. We use a HECI interface to disable the ME early in the boot process that should have a similar effect.

**Comment by leviport** [comment]
We will be bringing in some 5600MT/s RAM for testing. Once I receive them, I will test them and review this PR.

**Comment by ilikenwf** [comment]
> We will be bringing in some 5600MT/s RAM for testing. Once I receive them, I will test them and review this PR.

I'll take a photo once I reboot and run memtest86+ if you'd like despite. Regardless if all goes well it may give you another upgrade offering on the configuration page, or just an article boondoggle for phoronix when the next firmware update comes out.

> > As an unrelated aside, if I wanted to use the HAP bit to be sure ME was fully disabled as possible, do you happen to know the address for our ME image to set that bit? I realize it may mean 3W sleep instead of 1W, but it may be worth living with to quell my paranoia.
> > I know I've made a lot of noise but I am one of those people who gets joy out of experimenting with/customizing his tech, so I hope I don't become annoying.
> 
> I'm not sure of the HAP bit on 13th gen platforms. We use a HECI interface to disable the ME early in the boot process that should have a similar effect.

No sweat - there's a PR and some discusson around me_cleaner where they've had some hit and miss success with 16.X ME but the location of the HAP bit seems to sometimes vary. I'll do some digging - I trust that it is disabled since the OS says it is, but I don't trust that there's not some kind of bug or "bug" backdoor still going on. I have nothing to hide but am a "security as a hobby" person so I may keep looking into it, or just replace the WLAN card sometime with an Atheros.

Thank you all!

**Comment by leviport** [comment]
I received 1x16gb 5600 MT/s Crucial SODIMMs. `dmidecode` on bonw15 shows them running at 5600 MT/s as expected. I'm running some memory tests on it now, then I will also test them in serw13 and addw3.

**Comment by ilikenwf** [comment]
> > As an unrelated aside, if I wanted to use the HAP bit to be sure ME was fully disabled as possible, do you happen to know the address for our ME image to set that bit? I realize it may mean 3W sleep instead of 1W, but it may be worth living with to quell my paranoia.
> > I know I've made a lot of noise but I am one of those people who gets joy out of experimenting with/customizing his tech, so I hope I don't become annoying.
> 
> I'm not sure of the HAP bit on 13th gen platforms. We use a HECI interface to disable the ME early in the boot process that should have a similar effect.

For what it is worth, I have tested the setting of the bit per this me_cleaner PR:
https://github.com/corna/me_cleaner/pull/384

It works without issue...of course it looks/feels no different as it seems the HECI disable does at least hide the interface, if not fully truly disable IME...the author in that thread more recently says he's working on a way to remove any unnecessary modules, but having poked around in the IME image, it appears that System76 may have already customized it down to the most minimal configuration required to boot?

**Review by leviport — APPROVED** [review]
Memory tests are passing just fine on bonw15, addw3, and serw13, and all three show 5600 MT/s

**Pull request merged**
